sudo: required
services:
  - docker

addons:
  ssh_known_hosts: vps302914.ovh.net

before_install:
  - openssl aes-256-cbc -K $encrypted_80de618ab877_key -iv $encrypted_80de618ab877_iv -in deploy_rsa.enc -out deploy_rsa -d
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - MANIFMAKER_VERSION=$(cat manifmaker/package.json | grep version | head -1 | awk -F: \'{ print $2 }\' | sed \'s/[\",]//g\')
  - CONTAINER_NAME=manifaker_$MANIFMAKER_VERSION

script:
  - echo "Now building and delivering" $MANIFMAKER_VERSION
  #- cd manifmaker #will be app soon
  #- docker build -t assomaker/manifmaker:$MANIFMAKER_VERSION .
  #- docker push assomaker/manifmaker:$MANIFMAKER_VERSION
  - echo "Now deploying " $MANIFMAKER_VERSION
  - ssh root@vps302914.ovh.net "docker pull assomaker/manifmaker:$MANIFMAKER_VERSION"
  - ssh root@vps302914.ovh.net "docker stop $CONTAINER_NAME; docker rm -fv $CONTAINER_NAME"
  - ssh root@vps302914.ovh.net "docker run -d --name $CONTAINER_NAME -e ROOT_URL=http://manifmaker0-0.com -e MONGO_URL=mongodb://manifmaker0-0:manifmaker@manifmaker-mongo/manifmaker0-0 -p 8080:80 --link manifmaker-mongo assomaker/manifmaker:$MANIFMAKER_VERSION"


branches:
  only:
  - deploy
