sudo: required
services:
  - docker

addons:
  ssh_known_hosts: vps302914.ovh.net

before_install:
  - openssl aes-256-cbc -K $encrypted_80de618ab877_key -iv $encrypted_80de618ab877_iv
  - in deploy_rsa.enc -out deploy_rsa -d
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

script:
  #- cd manifmaker #will be app soon
  #- docker build -t assomaker/manifmaker:0.0 .
  #- docker push assomaker/manifmaker:0.0
  - ssh root@vps302914.ovh.net 'docker ps'
  #- ssh root@vps302914.ovh.net 'docker pull assomaker/manifmaker:0.0'
  #- ssh root@vps302914.ovh.net 'docker stop manifaker_0.0; docker rm -fv manifaker_0.0'
  #- ssh root@vps302914.ovh.net 'docker run -d --name manifaker_0.0 -e ROOT_URL=http://manifmaker0-0.com -e MONGO_URL=mongodb://manifmaker0-0:manifmaker@manifmaker-mongo/manifmaker0-0 -p 8080:80 --link manifmaker-mongo assomaker/manifmaker:0-0'



branches:
  only:
  - deploy
