sudo: required
services:
  - docker

addons:
  ssh_known_hosts: vps302914.ovh.net

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - chmod 700 scripts/get_version.sh
  - . scripts/get_version.sh
  - CONTAINER_NAME=manifmaker_$MANIFMAKER_VERSION
  - echo MANIFMAKER_VERSION=$MANIFMAKER_VERSION CONTAINER_NAME=$CONTAINER_NAME
  - openssl aes-256-cbc -K $encrypted_5cb4ad8e9b4e_key -iv $encrypted_5cb4ad8e9b4e_iv -in preprod_rsa.enc -out preprod_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/preprod_rsa
  - ssh-add $TRAVIS_BUILD_DIR/preprod_rsa


script:
  - cd app
  - echo "... Now building and delivering Docker image for " $MANIFMAKER_VERSION
  - docker build -t assomaker/manifmaker:$MANIFMAKER_VERSION .
  - docker push assomaker/manifmaker:$MANIFMAKER_VERSION
  - echo "... Now shipping " $MANIFMAKER_VERSION
  - ssh root@vps302914.ovh.net "docker pull assomaker/manifmaker:$MANIFMAKER_VERSION"
  - echo "... Now deploying to PreProd "
  - echo "!!! manifmaker repo need to be present AND production/docker-compose-preprod manifmaker image tag should be identical to app/package.json verion !!!"
  - ssh root@vps302914.ovh.net "cd manifmaker; git reset --hard HEAD; git pull origin deploy"
  - ssh root@vps302914.ovh.net "cd manifmaker/production; docker-compose --file docker-compose-preprod up -d manifmaker"

branches:
  only:
  - deploy
