sudo: required

services:
  - docker
  
  
before_install:
  - sudo apt-get install sshpass
  - #docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"


script :
  - sshpass -p '$STAGING_SSH_PWD' ssh -o "StrictHostKeyChecking no" root@vps302914.ovh.net 'docker ps'
  - sshpass -p '$STAGING_SSH_PWD' ssh root@vps302914.ovh.net 'docker pull assomaker/manifmaker:0.0'
  - sshpass -p '$STAGING_SSH_PWD' ssh root@vps302914.ovh.net 'docker stop manifaker_0.0; docker rm -fv manifaker_0.0'
  - sshpass -p '$STAGING_SSH_PWD' ssh root@vps302914.ovh.net 'docker run -d --name manifaker_0.0 -e ROOT_URL=http://manifmaker0-0.com -e MONGO_URL=mongodb://manifmaker0-0:manifmaker@manifmaker-mongo/manifmaker0-0 -p 8080:80 --link manifmaker-mongo assomaker/manifmaker:0-0'
  - #cd manifmaker #will be app soon
  - #docker build -t assomaker/manifmaker:0.0 .
  - #docker push assomaker/manifmaker:0.0


branches:
  only:
    - deploy
