sudo: required

services:
  - docker

script :
  - cd manifmaker #will be app soon
  - docker build -t assomaker/manifmaker:0.0 .
  - docker login -e="$" DOCKER_EMAIL-u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push assomaker/manifmaker:0.0
