version: '2'
services:
  manifmaker-mongo: 
    container_name: manifmaker-mongo
    ports:
    - "27017:27017"
    image: mongo
  dev_consul:    
    container_name: dev_consul
    ports:
    - "8500:8500"
    image: consul
  registrator:
    container_name: registrator
    ports:
    - "8500:8500"
    image: gliderlabs/registrator:latest
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    command: consul://localhost:8500
    network_mode: "host"
  manifmaker-nginx:
    container_name: manifmaker-nginx
    build: ./staging/nginx
    image: manifmaker-nginx
    ports:
      - "80:80"
    environment:
      - CONSUL=172.17.0.1:8500  
