version: '3'
services:
    mongodb:
        image: 'mongo:3.2.6'
        networks:
          - manifmaker

    mongodb_backup: #Main DB
        image: 'assomaker/mongodb_backup'
        environment:
            - CRON_TIME=20 3 * * * #Change to your favorite cron job schedule
            - MAX_BACKUPS=10
            - INIT_BACKUP=yes
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017 
            - MONGODB_USER=backupuser #backup user previously added in /admin database
            - MONGODB_PASS=backupuserPWD
        volumes:
            - backup:/backup #Change to the host folder where you want to store the backups
         networks:
            - manifmaker

    manifmaker: #Main App
        image: 'assomaker/manifmaker:0.3.1-node'
        environment:
            #- INJECT_ALL_DATA=true
            - ROOT_URL=http://preprod-manifmaker.remip.eu/
            - MONGO_URL=mongodb
            - MANIFMAKER_ENDPOINT=http://manifmaker:80
            - EXPORT_PDF_ENDPOINT=http://node_export_pdf:3030/export
            - NGINX_ENDPOINT=http://preprod-manifmaker.remip.eu/pdf/
            - PUBLIC_ACCESS=http://preprod-manifmaker.remip.eu
            - VIRTUAL_HOST=preprod-manifmaker.remip.eu #for nginx-proxy
        networks:
          - voc_network
          - manifmaker
        volumes:
            - images:/opt/meteor/dist/cfs/files/images

    node_export_pdf: #Node app that run wkhtmltopdf container
        container_name: node_export_pdf
        image: 'assomaker/export_pdf'
        environment: 
            - OUTPUTDIR=export_pdf     #w shared volume with Nginx
            - NETWORKMODE=manifmaker_network #on which network whhtmltopdf container will be created (should be one where manifmaker is reachable)
            - MANIFMAKER_ENDPOINT=http://manifmaker:3000 #to send pdf status 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
           - manifmaker

    nginx: #Expose generated PDF by full name only
        image: nginx
        container_name: nginx
        ports:
            - "80"
        volumes:
            - export_pdf:/usr/share/nginx/html/pdf
        networks:
          - manifmaker

volumes:
  backup:
  images:
  export_pdf:

networks:
  manifmaker:
  voc_network:
    external: true
