version: '2'
services:
  manifmaker_mongo: 
    ports:
    - "27017:27017"
    image: mongo
  dev_consul: 
    ports:
    - "8500:8500"
    image: consul
  registrator: 
    ports:
    - "8500:8500"
    image: gliderlabs/registrator:latest
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    command: consul://localhost:8500
    network_mode: "host"
  manifmaker-nginx:
    build: ./nginx
    image: manifmaker-nginx
    ports:
      - "80:80"
    environment:
      - CONSUL=172.17.0.1:8500  
