version: '2'
services:
    mongodb:
        image: 'mongo:3.2.6'
        container_name: production_mongodb
    mongodb_backup:
        container_name: mongodb_backup
        image: 'assomaker/mongodb_backup'
        environment:
            - CRON_TIME=20 3 * * * #Change to your favorate cron job schedule
            - MAX_BACKUPS=10
            - INIT_BACKUP=yes
            - MONGODB_HOST=production_mongodb
            - MONGODB_PORT=27017 
            - MONGODB_USER=backupuser #backup user previously added in /admin database
            - MONGODB_PASS=backupuserPWD
        volumes:
            - ~/manifmaker_backup:/backup #Change to the host folder where you want to store the backups
    manifmaker: 
        image: 'assomaker/manifmaker:0-2-2'
        environment:
            - ROOT_URL=http://preprod.manifmaker.24heures.org/
            - MONGO_URL=mongodb://manifmaker:manifmaker@production_mongodb/manifmaker #using manifmaker user in /manifmaker database
        ports: 
            - "80:3000" 
        volumes:
            - ~/manifmaker_images:/opt/meteor/dist/cfs/files/images

